# Site settings
title: Care with Confidence
email: ryan.d.price@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Care with confidence domain site, explains services and courses 
  available.

timezone: Europe/London
encoding: utf-8

# Build settings
markdown: kramdown

collections:
  courses:
    output: true
    permalink: /:collection/:name
  dates:
    output: true
    permalink: /:collection/:name

defaults:
-
  scope:
    path: ""
    type: "courses"
  values:
    layout: "course"
-
  scope:
    path: ""
    type: "dates"
  values:
    layout: "dates"
